# general setting
batch_size: 16
input_size: 320
backbone_type: 'MobileNetV2_0.35'  # 'ResNet50', 'MobileNetV2'
sub_name: 'retinaface_mbv2'

# training dataset
dataset_path: './data/bb_ir_320x320_train_bin.tfrecord'
dataset_len: 39312  # number of training samples
using_bin: True
using_flip: False
using_distort: True

# testing dataset
testing_dataset_path: './data/widerface/val'

# network
out_channel: 64

# anchor setting
min_sizes: [[8, 16], [32, 64], [128, 256]]
steps: [8, 16, 32]
match_thresh: 0.45
ignore_thresh: 0.3
variances: [0.1, 0.2]
clip: False

# training setting
epoch: 100
init_lr: !!float 1e-2
lr_decay_epoch: [50, 68]
lr_rate: 0.1
warmup_epoch: 5
min_lr: !!float 1e-3

weights_decay: !!float 5e-4
momentum: 0.9

pretrain: True

save_steps: 3000